# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VideoPath = QtWidgets.QLabel(self.centralwidget)
        self.VideoPath.setGeometry(QtCore.QRect(40, 220, 361, 80))
        self.VideoPath.setText("")
        self.VideoPath.setWordWrap(True)
        self.VideoPath.setObjectName("VideoPath")
        self.MaskDirPath = QtWidgets.QLabel(self.centralwidget)
        self.MaskDirPath.setGeometry(QtCore.QRect(40, 100, 361, 80))
        self.MaskDirPath.setMouseTracking(False)
        self.MaskDirPath.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MaskDirPath.setText("")
        self.MaskDirPath.setWordWrap(True)
        self.MaskDirPath.setObjectName("MaskDirPath")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(680, 110, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.ClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton.setGeometry(QtCore.QRect(680, 220, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.ClearButton.setFont(font)
        self.ClearButton.setObjectName("ClearButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 270, 151, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.VideoPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.VideoPathButton.setGeometry(QtCore.QRect(480, 220, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.VideoPathButton.setFont(font)
        self.VideoPathButton.setObjectName("VideoPathButton")
        self.MaskDirPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.MaskDirPathButton.setGeometry(QtCore.QRect(480, 110, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.MaskDirPathButton.setFont(font)
        self.MaskDirPathButton.setObjectName("MaskDirPathButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.LogLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogLabel.setEnabled(False)
        self.LogLabel.setGeometry(QtCore.QRect(90, 340, 581, 231))
        self.LogLabel.setText("")
        self.LogLabel.setObjectName("LogLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartButton.setText(_translate("MainWindow", "切割"))
        self.ClearButton.setText(_translate("MainWindow", "清除"))
        self.label_3.setText(_translate("MainWindow", "歷程"))
        self.VideoPathButton.setText(_translate("MainWindow", "瀏覽"))
        self.MaskDirPathButton.setText(_translate("MainWindow", "瀏覽"))
        self.label_4.setText(_translate("MainWindow", "背景圖"))
        self.label_5.setText(_translate("MainWindow", "影片檔"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
